### ISSUE TITLE
Any plan to update to MPAndroidChart v3

### ISSUE THREAD

**Issue by wuxudong** [mskec/react-native-mp-android-chart#12]
the latest MPAndroidChart  version is v3.0.1

**Comment by mskec** [comment]
Hi @wuxudong, is there something in v3.0.1 that you need and do not have in 2.x?
There are quite few breaking changes I would need to address.

**Comment by wuxudong** [comment]
I am quite new to MPAndroidChart. If there is any workaround or misunderstanding, please tell me.    
My data is not evenly spaced, for example, x data is [1,2,4,5,7,9,10].      
but in V2.x, xVals are string, so the chart is not correctly painted.

**Comment by wuxudong** [comment]
Hi, I create a fork at https://github.com/wuxudong/react-native-mp-android-chart

update to mpAndroidChart v3, 
you can view all the new feature at examples-> TimeSeriesLineChartScreen .

 I can create a pull request if you like.

**Comment by wuxudong** [comment]
I spent hours to fork the ios version, and update it to Charts V3 too. 

repo is at https://github.com/wuxudong/react-native-ios-charts

I have no experience of coding with swift & oc, so I can only fix compile error based on google and xcode hint. It took me hours. But finally it works.

the original repo has lots of duplication codes, a refactor should be applied later.

Charts and MpAndroidChart is equal, expect one day can merge the two react-native wrapper lib together.

**Comment by mskec** [comment]
I had the same idea when I published this lib, but I also do not have experience with swift/oc so I didn't proceeded with it. 
It would definitely be awesome if we could merge ios and android libs, but that would require merging APIs and components for which swift/os knowledge is required.

**Comment by wuxudong** [comment]
Do you mind if I create a new repo and copy some code of this repo?

I will make a try to merge android/ios lib on the new repo, there must be some of breaking api changes.

**Comment by mskec** [comment]
@wuxudong this lib is published with [MIT license](https://tldrlegal.com/license/mit-license).

**Comment by wuxudong** [comment]
A stupid question: 

android part is base on your project(licensed by MIT mskec),   
ios part is base on another project(licensed by MIT foo).  
and I make some contribution, maybe just some modification of existing code.

what is the correct approach to license the new project?

**Comment by mskec** [comment]
hmm good question.
Maybe you can do something like this https://github.com/XaminProject/handlebars.php/issues/57#issuecomment-37617369

**Comment by wuxudong** [comment]
Hi, I create a repo at https://github.com/wuxudong/react-native-charts-wrapper
If you have any question, do tell me.
