### ISSUE TITLE
Problem with running

### ISSUE THREAD

**Issue by DanielWalendzewicz** [mskec/react-native-mp-android-chart#16]
I've problem, when i'm trying to run my app im getting this error :  
![zrzut ekranu 2018-08-14 o 21 28 24](https://user-images.githubusercontent.com/22885884/44113641-085014f0-a009-11e8-8ee7-55098b0dea33.png)

Here is my code : 

import React from 'react';
import {Modal,View,Text,Button, StyleSheet, Dimensions} from 'react-native';
import {BarChart} from 'react-native-mp-android-chart';

const deviceWidth = Dimensions.get('window').width;
const deviceHeight = Dimensions.get('window').height;

const MarkerDetail = (props) => {

    let modalContent = null;

    let variable = {
        data: {
            datasets: [{
                yValues: [100, 105, 102, 110],
                label: 'Data set 1',
                config: {
                    color: 'teal'
                }
            }, {
                yValues: [110, 100, 105, 108],
                label: 'Data set 2',
                config: {
                    color: 'orange'
                }
            }],
            xValues: ['Q1', 'Q2', 'Q3', 'Q4']
        }
    };

    if(props.selectedStation){
        modalContent = (
            <View >
                <View style = {styles.headerBar}>
            <Text style ={styles.header}>{props.selectedStation.stationName}
            </Text>
                <Button title="X" style = {styles.closeButton}
                        onPress = {props.onModalClosed}
                        color= "#2dc997"
                />
                </View>
                <View>
                    <BarChart
                        style={styles.chart}
                        data={variable.data}
                        animation={{durationX: 2000}}
                    />
                </View>
            </View>
        );
    }

    return(
      <Modal visible ={props.selectedStation !== null}  animationType={"slide"}>
          <View style = {styles.modalContainer}>
              {modalContent}
          </View>
      </Modal>
    );

};

const styles = StyleSheet.create({
   modalContainer: {
       width: deviceWidth,
       height: deviceHeight
   },
    headerBar: {
        backgroundColor: '#2dc997',
        height: deviceHeight / 20,
        marginTop: 5,
        flexDirection:'row',
        flexWrap:'wrap'
    },
    header: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 20,
        textAlign: 'center',
        padding: 3,
        width: deviceWidth * 9 /10

    },
    closeButton: {
        width: deviceWidth * 1/ 10,
        color : '#2dc997',
    },
    chart: {
        height: deviceHeight / 8,
        width: 300
    }
});

export default MarkerDetail;

Anny suggestion ? I was trying to do it by google suggestions but im stuck

**Comment by mskec** [comment]
Hi @DanielWalendzewicz, 
The problem is that this library is not maintained and wasn't updated to use PropTypes from the new package. Since React v15.5 they moved PropTypes [here](https://www.npmjs.com/package/prop-types).

I suggest you to use this library instead, it has the same android code and additionally support for ios. https://github.com/wuxudong/react-native-charts-wrapper
