### ISSUE TITLE
Prevent user interactions (tap and zoom)

### ISSUE THREAD

**Issue by guitoof** [mskec/react-native-mp-android-chart#2]
Hi there @mskec !

Great job integrating the MPAndroidChart lib in React-Native.
I was wondering if there is a way to prevent user interactions such as taps and zooms on the graphs ?

Thx for your answer,
Have a nice day

**Comment by mskec** [comment]
Hi @guitoof,

I am glad you find it useful.

Unfortunately I didn't have time to implement interaction settings.
These are setting that underlaying library supports https://github.com/PhilJay/MPAndroidChart/wiki/Interaction-with-the-Chart so in theory it can be implemented.

I do not have much time at this moment, but if I have some I will implement it at some point.
If you want to implement it, feel free to make a PR and I will be happy to merge it.

Have a nice day

**Comment by guitoof** [comment]
Hi @mskec thanks a lot for your quick response.
I'm not sure I'll have the time to implement it but I will try ;)

Thanks again

**Comment by mskec** [comment]
Hi again @guitoof, 

I am happy to let you know that I implemented interaction settings.

You can find available settings in this commit: https://github.com/mskec/react-native-mp-android-chart/commit/33ef8e94fd5ace9c5a2ee5487592d0b874abb83c
