### ISSUE TITLE
Cannot read property 'bool' of undefined

### ISSUE THREAD

**Issue by TechnologiesP** [mskec/react-native-mp-android-chart#21]
While running the application after adding mp library getting the following Error

Application app has not been registered.

Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').

This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent

![Screenshot_1565154229](https://user-images.githubusercontent.com/44367302/62596199-e71aad80-b8fe-11e9-8585-759debe7209c.png)

**Comment by mskec** [comment]
This library is no longer maintained for some time. Please use this one https://github.com/wuxudong/react-native-charts-wrapper, it has the same android capabilities and more
