### ISSUE TITLE
Error while updating property 'data' of a view managed by: MPAndroidBarChart

### ISSUE THREAD

**Issue by alexkendall** [mskec/react-native-mp-android-chart#5]
I get this Error when running the example. RN 0.34

**Comment by mskec** [comment]
Hi @alexkendall,

I tried with RN 0.34.0 and 0.34.1 and I am not experiencing this error.
Can you give more details how to reproduce it?

**Comment by yayolius** [comment]
it happened to me when i was triying to update the data without using the this.setState(reactAddonsUpdate(... part of the example code, once i added and used like it should, it worked nicely
