### ISSUE TITLE
Limit Lines and colors support 

### ISSUE THREAD

**Issue by summersky92** [mskec/react-native-mp-android-chart#6]
Able to pass in the limit line value but not able to create a limit line, also the multiple colors for the line chart.

https://github.com/PhilJay/MPAndroidChart/wiki/The-Axis#limit-lines in the android can implement like this:
LimitLine xLimitLine = new LimitLine(4f,"xLTest")
xLimitLine.setLineColor(Color.GREEN);
xLimitLine.setTextColor(Color.GREEN);
xAxis.addLimitLine(xLimitLine);

**Comment by mskec** [comment]
Hi @summersky92, please take a look at "Candle Stick chart" [screen in example](https://github.com/mskec/react-native-mp-android-chart-example/blob/master/app/CandleStickChartScreen.js). There you will see how to set limit lines.

Check line [chart example](https://github.com/mskec/react-native-mp-android-chart-example/blob/master/app/LineChartScreen.js) for how to use multiple colors.
