### ISSUE TITLE
Update pie chart data

### ISSUE THREAD

**Issue by ncampos92** [mskec/react-native-mp-android-chart#7]
I'm getting this error when updating data of a pie chart that is being obtained from a database.

"Error while updating property 'data' of a view managed by: MPAndroidPieChart"

**Comment by mskec** [comment]
Are you sure your data is correctly formatted?
[Check example](https://github.com/mskec/react-native-mp-android-chart-example/blob/master/app/PieChartScreen.js) for correct data config.

**Comment by ncampos92** [comment]
The problem was that i got invalid data from the database.

Thanks!
