### ISSUE TITLE
IMarker usage

### ISSUE THREAD

**Issue by ncampos92** [mskec/react-native-mp-android-chart#8]
Is it possible to use the IMarker interface in react native, how do you implement it?

**Comment by mskec** [comment]
It's not implemented in this lib.
If you have time feel free to implement it. [IMarker WIKI](https://github.com/PhilJay/MPAndroidChart/wiki/IMarker-Interface)

**Comment by cesardeazevedo** [comment]
i've created a pull request https://github.com/mskec/react-native-mp-android-chart/pull/10
