### ISSUE TITLE
How can i add a gradient as background?

### ISSUE THREAD

**Issue by yayolius** [mskec/react-native-mp-android-chart#9]
I am triying to imitate this issue: https://github.com/PhilJay/MPAndroidChart/issues/104

That is shown in this example image in MPAndroidChart home page
https://camo.githubusercontent.com/e9f3408cc22c2896a897e9ed92a2fd2cbcf40493/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d50416e64726f696443686172742f6d61737465722f73637265656e73686f74732f6c696e655f63686172745f6772616469656e742e706e67

Is it possible to do it in react native?

Another question, it is possible to hide the label color icon?, i use an empty label but it stills shows it.

Thanks
Claudio

**Comment by mskec** [comment]
For labels check out this file to see all available configs: https://github.com/mskec/react-native-mp-android-chart/blob/master/lib/ChartBase.js#L53

Unfortunately gradient color configuration is not implemented in this library.

**Comment by yayolius** [comment]
About the gradient its ok, but about the label that goes in each point i am not talking about the leyend but the labels, i can only disable them with

```
        xAxis: {
            drawLabels: false,
        },
        yAxis: {
          left: {
            drawLabels: false,
          },
          right: {
            enabled: false
          },
        },
```

**Comment by mskec** [comment]
oh right. I mistook labels for legend.

`drawLabels: false` should be the way to disable labels on axis points.

I am not sure what do you mean by "label color icon", can you show me screenshot with what exactly you would like to disable?

**Comment by yayolius** [comment]
Sorry for the delay, i am talking about the values that appear in the circles of the LineChart, i can just disable them with drawValues: false, in this example:

```
            datasets: [{
                        yValues: yValues,
                        label: '',
                        config: {
                          lineWidth: 5,
                          drawCircles: true,
                          drawCubic: true,
                          circleColor:'white',
                          color: 'white',
                          drawFilled: true,
                          fillColor: '#2e97de',
                          fillAlpha: 60, 
                          drawValues: false
                        }
                      }],
                  xValues: xValues
```

By the way, where do i have to set the axisMinValue for the Y axis, because it does not matter where i put it it does not work.

Thanks Again

**Comment by mskec** [comment]
Yep, that is how to disable them. https://github.com/PhilJay/MPAndroidChart/wiki/The-DataSet-class

You can set Y axis `axisMinValue` just by adding it to yAxis config object.

``` lang=javascrip
<CandleStickChart
  yAxis={{ axisMinValue: 95 }}
/>
```
